### ISSUE TITLE
Disable github pages

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/docs#14]
Can you:
- disable github pages on this repository
- remove the CNAME record for https://docs.stanforddaily.com/
- remove secrets from this repo
- remove the IAM user in AWS that the secrets in this repo corresponded to

Everything has now been moved to notion.

**Comment by sbcatania** [comment]
Hey did the first two things, there were no secrets in github I could find though, and thus not sure about the last one. Any tips?

**Comment by epicfaace** [comment]
Oh, right, looking at the github actions workflow file (https://github.com/TheStanfordDaily/docs/blob/f1023664c73d8e51a8d4c2b21b558140215e2375/.github/workflows/deploy.yml), there are no secrets because this repo didn't deploy to AWS, but rather it just deployed to github pages. I think that's all the cleanup we need, then.
